#!/bin/bash
#
# Copyright 2019 The Triple Banana Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

. $TOOLS_PATH/common/chromium.sh
. $TOOLS_PATH/common/path.sh
. $TOOLS_PATH/common/stack_dir.sh

push_dir $(chromium_path)

git stash && echo &&
git apply $(triple_banana_upstream_path)/*.patch \
    --3way \
    --verbose &&
git commit -m "Triple Banana $(get_chromium_version)"

pop_dir
