#!/bin/bash
#
# Copyright 2019 The Triple Banana Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

. $TOOLS_PATH/common/path.sh
. $TOOLS_PATH/common/stack_dir.sh
. $TOOLS_PATH/common/version.sh

function get_upstream_change_list() {
  push_dir $(triple_banana_upstream_path)
  ls $(triple_banana_upstream_path)/*.patch
  pop_dir
}

function check_patch() {
  local patch_file=$1
  git apply --check --3way $patch_file
  return $?
}

function apply_patch() {
  local patch_file=$1
  git apply --3way $patch_file
  return $?
}

function apply_patches() {
  push_dir $(chromium_path)
  local success=true
  for change in $(get_upstream_change_list); do
    echo "Patching $change..."
    if check_patch $change; then
      apply_patch $change
    else
      success=false
    fi
    echo
  done
  write_version_file
  if $success; then
    git add $(chromium_path)/chrome/VERSION
    git commit -m "Triple Banana $(get_triple_banana_version)"
  fi
  pop_dir
}

apply_patches
