#!/bin/bash
#
# Copyright 2019 The Triple Banana Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

. $TOOLS_PATH/common/path.sh
. $TOOLS_PATH/common/stack_dir.sh
. $TOOLS_PATH/common/version.sh

function gn_gen() {
  local build_target=$1
  local use_goma=$2
  local arch_type=$3
  local gn_args=$(cat $(triple_banana_build_gn_path)/$build_target.gn)

  if [ "$use_goma" = true ]; then
    gn_args="$gn_args use_goma = true goma_dir = \"$GOMA_DIR\""
  fi

  if [ "$arch_type" = 64 ]; then
    gn_args="$gn_args target_cpu=\"arm64\""
  fi

  push_dir $(chromium_path)
  gn gen out/$build_target$arch_type --args="$gn_args"
  pop_dir
}

function ninja_build() {
  local build_target=$1
  local job_flags=$2

  push_dir $(chromium_path)
  autoninja $job_flags -C out/$build_target$arch_type triple_banana
  pop_dir
}

build_target="debug"
use_goma=false
arch_type="32"

for option in "$@"; do
  case $option in
    --goma)
      use_goma=true
      shift
    ;;
    --release)
      build_target="release"
      shift
    ;;
    --no-gen)
      disable_gn_gen=true
      shift
    ;;
    --64bit)
      arch_type="64"
      shift
    ;;
    -j*)
      if [ "${2:0:1}" = "-" ]; then
        job_flags="$1"
      else
        job_flags="$1$2"
      fi
      shift 2
    ;;
esac
done

if [ "$disable_gn_gen" != true ]; then
  echo "Configuration for out/$build_target$arch_type build..."
  gn_gen $build_target $use_goma $arch_type
fi
ninja_build $build_target $job_flags
