#!/bin/bash
#
# Copyright 2019 The Triple Banana Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

. $TOOLS_PATH/common/path.sh
. $TOOLS_PATH/common/stack_dir.sh

function clear_override_strings() {
  push_dir $(override_resource_path)
  find $(override_resource_path) -name "override_strings.xml" -exec rm {} \;
  find $(override_resource_path) -type d -empty -delete
  pop_dir
}

function read_target_strings() {
  push_dir $(chromium_path)
  input_paths=$(find $(chromium_out_release_path)/gen -name "*strings.xml")
  for input_path in $input_paths; do
    echo "Read $input_path..."
    localized_path=$(basename $(dirname $input_path))
    mkdir -p $(override_resource_path)/$localized_path
    awk '/(<string.*>.*Chrome.*)/,/(<\/string>)/' \
        $input_path \
        >> $(override_resource_path)/$localized_path/override_strings.xml
  done

  override_strings_paths=$(find $(override_resource_path) -name "override_strings.xml")
  for override_string_path in $override_strings_paths; do
    echo "Write $override_string_path..."
    echo -e "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<resources>" > $override_string_path.tmp
    cat $override_string_path >> $override_string_path.tmp
    echo "</resources>" >> $override_string_path.tmp
    mv $override_string_path.tmp $override_string_path
  done
  pop_dir
}

function rewrite_banana_strings() {
  strings_path=$1/override_strings.xml
  pattern=$2

  # Rewrite for override_strings.xml
  echo "Rewrite $strings_path with \"$pattern\"..."
  sed "$pattern" $strings_path > $strings_path.tmp
  mv $strings_path.tmp $strings_path
}

function main() {
  clear_override_strings
  read_target_strings

  strings_paths=$(ls -d $(override_resource_path)/values*)
  for strings_path in $strings_paths; do
    rewrite_banana_strings $strings_path "s/Chrome/Banana Browser/g"
  done

  # Fix postpositions in Korean translation
  rewrite_banana_strings "$(override_resource_path)/values-ko" \
      "s/Banana Browser이/Banana Browser가/g"
  rewrite_banana_strings "$(override_resource_path)/values-ko" \
      "s/Banana Browser은/Banana Browser는/g"
  rewrite_banana_strings "$(override_resource_path)/values-ko" \
      "s/Banana Browser을/Banana Browser를/g"

  # Fix upstream bug in French translation
  rewrite_banana_strings "$(override_resource_path)/values-fr" \
      "s/60 % de/60 \\\% de/g"
}

main $1
