#!/bin/bash
#
# Copyright 2019 The Triple Banana Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

. $TOOLS_PATH/common/path.sh
. $TOOLS_PATH/common/stack_dir.sh
. $TOOLS_PATH/common/version.sh

function reset_upstream_patches() {
  push_dir $(triple_banana_upstream_path)
  rm -f *.patch
  pop_dir
}

function update_upstream_patches() {
  push_dir $(chromium_path)

  git diff refs/tags/$(get_chromium_version) \
      --src-prefix="tb/" \
      --dst-prefix="tb_diff/" \
      | sed -r "/^index\ [a-z|0-9]+\.\.[a-z|0-9]+[\ ]?[0-9]*$/d" \
      > /tmp/triple_banana.patch &&
  push_dir $(triple_banana_upstream_path) &&
  splitdiff -a -d /tmp/triple_banana.patch &&
  pop_dir

  pop_dir
}

reset_upstream_patches && update_upstream_patches
