#!/bin/bash
#
# Copyright 2019 The Triple Banana Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

. $TOOLS_PATH/common/path.sh
. $TOOLS_PATH/common/stack_dir.sh

function reset_upstream_patches() {
  push_dir $(triple_banana_upstream_path)
  rm -f *.patch
  pop_dir
}

function update_upstream_patches() {
  push_dir $(chromium_path)

  git format-patch origin/master \
      --src-prefix="triple_banana/" \
      --dst-prefix="triple_banana_change/" \
      --stdout > /tmp/triple_banana.patch &&
  push_dir $(triple_banana_upstream_path) &&
  splitdiff -a -d /tmp/triple_banana.patch &&
  pop_dir

  pop_dir
}

reset_upstream_patches && update_upstream_patches
