#!/bin/bash
#
# Copyright 2019 The Triple Banana Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

. $TOOLS_PATH/common/path.sh
. $TOOLS_PATH/common/stack_dir.sh
. $TOOLS_PATH/common/version.sh

function make_base_branch() {
  push_dir $(chromium_path)
  echo "Fetching refs/tags/$(get_chromium_version)..."
  git fetch origin refs/tags/$(get_chromium_version) &&
  git checkout -B triple_banana_$(get_chromium_version) \
      refs/tags/$(get_chromium_version) &&
  rm -rf $(chromium_path)/third_party/devtools-frontend/src &&
  gclient sync --with_branch_heads --with_tags
  pop_dir
  return $?
}

make_base_branch && $(triple_banana_tools_path)/banana apply_upstream
