#!/bin/bash
#
# Copyright 2019 The Triple Banana Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

export TOOLS_PATH=$(cd $(dirname $BASH_SOURCE); pwd)
source $TOOLS_PATH/banana.sh $@;
