#!/bin/bash
#
# Copyright 2019 The Triple Banana Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

export TRIPLE_BANANA_TOOLS_PATH=$(cd $(dirname $BASH_SOURCE); pwd)
export TRIPLE_BANANA_PATH=$(realpath $TRIPLE_BANANA_TOOLS_PATH/..)
export CHROMIUM_SRC_PATH=$(realpath $TRIPLE_BANANA_TOOLS_PATH/../..)

pushd $CHROMIUM_SRC_PATH > /dev/null &&
git diff --src-prefix="triple_banana/" --dst-prefix="triple_banana_change/" > /tmp/triple_banana.patch &&
pushd $TRIPLE_BANANA_PATH/upstream > /dev/null &&
rm *.patch &&
splitdiff -a -d /tmp/triple_banana.patch &&
popd > /dev/null &&
popd > /dev/null
